# Generated by Django 3.0.1 on 2019-12-28 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
        ('predios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='predio',
            name='pastor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pastor_do_predio', to='pessoas.Pessoa'),
        ),
    ]
