# Generated by Django 3.0.1 on 2019-12-28 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('predios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FuncaoLideranca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('A', 'Apóstolo'), ('D', 'Discipulador'), ('L', 'Líder'), ('P', 'Pastor'), ('O', 'Obreiro')], max_length=1)),
                ('descricao', models.CharField(max_length=100)),
                ('atribuicoes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Função Liderança',
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_cpf', models.CharField(max_length=14, unique=True)),
                ('nome', models.CharField(max_length=150)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('celular', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('cep', models.CharField(blank=True, max_length=9, null=True)),
                ('rua', models.CharField(blank=True, max_length=200, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('bairro', models.CharField(blank=True, max_length=50, null=True)),
                ('cidade', models.CharField(blank=True, max_length=50, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('pais', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_pessoa', models.CharField(choices=[('V', 'Visitante'), ('F', 'Frequentador'), ('M', 'Membro')], default='V', max_length=1)),
                ('situacao', models.CharField(blank=True, choices=[('A', 'Ativo'), ('I', 'Inativo')], max_length=1, null=True)),
                ('foto_perfil', models.FileField(blank=True, null=True, upload_to='foto_perfil')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Data Cadastro')),
                ('updated', models.DateField(auto_now=True, verbose_name='Data Atualização')),
                ('funcao_lideranca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pessoas.FuncaoLideranca', verbose_name='Função Liderança')),
                ('predio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predios.Predio', verbose_name='Prédio')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
