# Generated by Django 3.0.1 on 2020-02-29 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0009_auto_20200205_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcaolideranca',
            name='categoria',
            field=models.CharField(choices=[('A', 'Apóstolo'), ('P', 'Pastor'), ('O', 'Obreiro'), ('D', 'Discipulador'), ('L', 'Líder')], max_length=1),
        ),
    ]
