# Generated by Django 3.0.1 on 2020-01-22 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predios', '0003_auto_20191229_2036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predio',
            old_name='cnpj',
            new_name='num_cnpj',
        ),
        migrations.AddField(
            model_name='predio',
            name='complemento',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
