# Generated by Django 3.0.1 on 2020-01-22 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predios', '0004_auto_20200121_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='predio',
            name='situacao',
            field=models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1),
        ),
    ]
