# Generated by Django 3.0.1 on 2020-02-05 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predios', '0005_predio_situacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='predio',
            name='lat',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='predio',
            name='lng',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
