# Generated by Django 3.0.1 on 2020-03-05 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predios', '0006_auto_20200205_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predio',
            name='situacao',
        ),
        migrations.AddField(
            model_name='predio',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
