# Generated by Django 3.0.1 on 2019-12-29 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predios', '0002_predio_pastor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pessoas', '0002_auto_20191228_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='funcao_lideranca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pessoas.FuncaoLideranca', verbose_name='Função Liderança'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='predio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='predios.Predio', verbose_name='Prédio'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
