# Generated by Django 3.0.1 on 2020-01-05 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0003_auto_20191229_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='complemento',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
