# Generated by Django 3.0.1 on 2020-01-07 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0004_pessoa_complemento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='celular',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
