# Generated by Django 3.0.1 on 2020-01-15 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0006_auto_20200107_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='situacao',
            field=models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='tipo_pessoa',
            field=models.CharField(choices=[('V', 'Visitante'), ('F', 'Frequentador'), ('M', 'Membro')], default='M', max_length=1),
        ),
    ]
