# Generated by Django 3.0.1 on 2020-02-07 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pequenos_grupos', '0002_auto_20200124_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='celula',
            name='lat',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='celula',
            name='lng',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
