# Generated by Django 3.0.1 on 2020-02-29 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0010_auto_20200229_0344'),
        ('pequenos_grupos', '0003_auto_20200206_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='celula',
            name='participantes',
            field=models.ManyToManyField(blank=True, null=True, to='pessoas.Pessoa'),
        ),
    ]
