# Generated by Django 3.0.1 on 2020-03-02 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0011_auto_20200302_0205'),
        ('pequenos_grupos', '0004_celula_participantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celula',
            name='participantes',
            field=models.ManyToManyField(to='pessoas.Pessoa'),
        ),
    ]
