# Generated by Django 3.0.1 on 2020-03-07 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0012_auto_20200304_2251'),
        ('pequenos_grupos', '0004_celula_participantes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='celula',
            name='situacao',
        ),
        migrations.AddField(
            model_name='celula',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='celula',
            name='participantes',
            field=models.ManyToManyField(to='pessoas.Pessoa'),
        ),
        migrations.CreateModel(
            name='ReuniaoCelula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('foto_reuniao_celula', models.ImageField(blank=True, null=True, upload_to='foto_reuniao_celula')),
                ('realizada', models.BooleanField(default=False)),
                ('celula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pequenos_grupos.Celula', verbose_name='Celula')),
            ],
        ),
    ]
